
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nn
 */
public class Menu extends javax.swing.JFrame {

    private final League league;
    private final DefaultListModel<String> listPreviewTeams;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        league = new League();
        listPreviewTeams = new DefaultListModel<>();
        jListTeams.setModel(listPreviewTeams);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFieldTeamName = new javax.swing.JTextField();
        jAddTeam = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListTeams = new javax.swing.JList<>();
        jDeleteTeam = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPositionTable = new javax.swing.JTable();
        jReset = new javax.swing.JButton();
        jLabelTablePosition = new javax.swing.JLabel();
        jSimulateMatch = new javax.swing.JButton();
        jLabelWinner = new javax.swing.JLabel();
        jLabelImage = new javax.swing.JLabel();
        jLabelEnterName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("DIN Condensed", 1, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("COLOMBIAN SOCCER LEAGUE");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 810, 60));

        jLabel2.setFont(new java.awt.Font("DIN Alternate", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Registered teams");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, 190, -1));

        textFieldTeamName.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        textFieldTeamName.setForeground(new java.awt.Color(204, 204, 204));
        textFieldTeamName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldTeamName.setText("Enter your team name");
        textFieldTeamName.setToolTipText("");
        textFieldTeamName.setBorder(null);
        textFieldTeamName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textFieldTeamNameMousePressed(evt);
            }
        });
        jPanel1.add(textFieldTeamName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 280, -1));

        jAddTeam.setBackground(new java.awt.Color(153, 255, 153));
        jAddTeam.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jAddTeam.setText("Add Team");
        jAddTeam.setBorderPainted(false);
        jAddTeam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jAddTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddTeam(evt);
            }
        });
        jPanel1.add(jAddTeam, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, -1));

        jListTeams.setBorder(null);
        jListTeams.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jListTeams.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListTeams.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListTeams.setToolTipText("");
        jScrollPane1.setViewportView(jListTeams);
        jListTeams.getAccessibleContext().setAccessibleDescription("");

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 350, 120));

        jDeleteTeam.setBackground(new java.awt.Color(255, 102, 102));
        jDeleteTeam.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jDeleteTeam.setText("Delete Team");
        jDeleteTeam.setBorderPainted(false);
        jDeleteTeam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jDeleteTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteTeam(evt);
            }
        });
        jPanel1.add(jDeleteTeam, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 250, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);
        jSeparator1.setAutoscrolls(true);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 280, 20));

        jPositionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Team Name", "Points Total", "Games Played", "Games Won", "Games Lost", "Goals Scored", "Goals Conceded"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jPositionTable.setAutoscrolls(false);
        jPositionTable.setEnabled(false);
        jPositionTable.setFocusTraversalKeysEnabled(false);
        jPositionTable.setFocusable(false);
        jPositionTable.setGridColor(new java.awt.Color(255, 255, 255));
        jPositionTable.setOpaque(false);
        jPositionTable.setRequestFocusEnabled(false);
        jPositionTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jPositionTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jPositionTable);
        if (jPositionTable.getColumnModel().getColumnCount() > 0) {
            jPositionTable.getColumnModel().getColumn(0).setResizable(false);
            jPositionTable.getColumnModel().getColumn(1).setResizable(false);
            jPositionTable.getColumnModel().getColumn(2).setResizable(false);
            jPositionTable.getColumnModel().getColumn(3).setResizable(false);
            jPositionTable.getColumnModel().getColumn(4).setResizable(false);
            jPositionTable.getColumnModel().getColumn(5).setResizable(false);
            jPositionTable.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 750, 139));

        jReset.setBackground(new java.awt.Color(255, 255, 51));
        jReset.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jReset.setText("Reset League");
        jReset.setBorderPainted(false);
        jReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetActionPerformed(evt);
            }
        });
        jPanel1.add(jReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, -1, -1));

        jLabelTablePosition.setFont(new java.awt.Font("DIN Condensed", 1, 30)); // NOI18N
        jLabelTablePosition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTablePosition.setText("Results of the matches");
        jPanel1.add(jLabelTablePosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 750, -1));

        jSimulateMatch.setBackground(new java.awt.Color(0, 255, 0));
        jSimulateMatch.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jSimulateMatch.setText("Simulate Match");
        jSimulateMatch.setBorderPainted(false);
        jSimulateMatch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSimulateMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSimulateMatch(evt);
            }
        });
        jPanel1.add(jSimulateMatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, -1, -1));

        jLabelWinner.setFont(new java.awt.Font("PT Serif", 1, 30)); // NOI18N
        jLabelWinner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWinner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icons8-hombre-ganador-48.png"))); // NOI18N
        jLabelWinner.setText("Team Winner:");
        jPanel1.add(jLabelWinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 800, -1));

        jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/colombian-national-soccer-team.jpg"))); // NOI18N
        jLabelImage.setText("jLabel4");
        jLabelImage.setOpaque(true);
        jPanel1.add(jLabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 390, 620));

        jLabelEnterName.setFont(new java.awt.Font("DIN Alternate", 1, 16)); // NOI18N
        jLabelEnterName.setText("Team name");
        jLabelEnterName.setToolTipText("");
        jPanel1.add(jLabelEnterName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 270, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAddTeam(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddTeam
        String teamName = textFieldTeamName.getText();
        teamName = teamName.toUpperCase();

        if (listPreviewTeams.contains(teamName)) {
            JOptionPane.showMessageDialog(this, "The equipment already exists. Try another team name.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!teamName.isEmpty()) {
            Team team = new Team(teamName);
            league.addLeagueTeam(team);
            listPreviewTeams.addElement(team.getNameTeam());

            DefaultTableModel model = (DefaultTableModel) jPositionTable.getModel();
            model.addRow(new Object[]{team.getNameTeam(), team.getPointsTotal(), team.getGamesPlayed(), team.getGamesWon(), team.getGamesLost(), team.getGoalsScored(), team.getGoalsConceded()});

            JOptionPane.showMessageDialog(this, "Team name successfully added.", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Please enter the team name.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jAddTeam

    private void jSimulateMatch(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSimulateMatch
        List<Team> lstTeams = league.getLstTeams();
        int numTeams = lstTeams.size();

        if (numTeams < 2) {
            JOptionPane.showMessageDialog(this, "At least two teams are needed to do the simulation.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        for (int i = 0; i < lstTeams.size(); i++) {
            Team teamOne = lstTeams.get(i);
            for (int x = 0; x < lstTeams.size(); x++) {
                Team teamTwo = lstTeams.get(x);
                if (teamTwo != teamOne) {
                    Match match = new Match(teamOne, teamTwo);
                    match.playMatch(jPositionTable, i, x);
                }
            }
        }

        //Show league winning team
        int winner = Integer.MIN_VALUE;
        String teamNameWinner = null;

        DefaultTableModel model = (DefaultTableModel) jPositionTable.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {
            int points = (int) model.getValueAt(i, 1);

            if (points > winner) {
                winner = points;
                teamNameWinner = (String) model.getValueAt(i, 0);
            }
        }
        jLabelWinner.setText("The winning team is:" + teamNameWinner);
        JOptionPane.showMessageDialog(this, "The winning team is: " + teamNameWinner, "Result of the match", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jSimulateMatch

    private void jDeleteTeam(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteTeam
        int selectedIndex = jListTeams.getSelectedIndex();

        if (selectedIndex != -1) {
            String selectedTeam = listPreviewTeams.getElementAt(selectedIndex);
            listPreviewTeams.removeElementAt(selectedIndex);

            league.deleteTeam(selectedTeam);

            DefaultTableModel model = (DefaultTableModel) jPositionTable.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                Object value = model.getValueAt(i, 0);
                if (value != null && value.equals(selectedTeam)) {
                    model.removeRow(i);
                    break;
                }
            }

            JOptionPane.showMessageDialog(this, "Team eliminated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a device from the list to delete it.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jDeleteTeam

    private void jResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetActionPerformed
        league.reset();
        listPreviewTeams.clear();
        DefaultTableModel model = (DefaultTableModel) jPositionTable.getModel();
        model.setRowCount(0);
        jLabelWinner.setText("Team Winner");
    }//GEN-LAST:event_jResetActionPerformed

    private void textFieldTeamNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldTeamNameMousePressed
        textFieldTeamName.setText ("");
        textFieldTeamName.setForeground(Color.black);       
    }//GEN-LAST:event_textFieldTeamNameMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddTeam;
    private javax.swing.JButton jDeleteTeam;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelEnterName;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelTablePosition;
    private javax.swing.JLabel jLabelWinner;
    private javax.swing.JList<String> jListTeams;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jPositionTable;
    private javax.swing.JButton jReset;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jSimulateMatch;
    private javax.swing.JTextField textFieldTeamName;
    // End of variables declaration//GEN-END:variables
    
}
